apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ebs-pvc-new
spec:
  accessModes:
    - ReadWriteOnce          # EBS only supports RWO
  storageClassName: ebs-sc-new   # Use the StorageClass
  resources:
    requests:
      storage: 10Gi
