apiVersion: v1
kind: PersistentVolume
metadata:
  name: efs-pv
spec:
  capacity:
    storage: 10Gi  # Dummy value, EFS is elastic
  volumeMode: Filesystem
  accessModes:
    - ReadWriteMany  # RWX for multi-pod access
  persistentVolumeReclaimPolicy: Retain
  storageClassName: efs-sc
  csi:
    driver: efs.csi.aws.com
    volumeHandle: fs-094697a5d69b20984  # Your EFS File System ID
