apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: efs-pvc
spec:
  accessModes:
    - ReadWriteMany  # Multiple pods can mount it
  resources:
    requests:
      storage: 5Gi  # Dummy value, EFS is elastic
  storageClassName: efs-sc
