apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ipl-reader-binding
  namespace: ipl
subjects:
- kind: User
  name: test-user
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: ipl-reader
  apiGroup: rbac.authorization.k8s.io
