apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ipl-reader
  namespace: ipl
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  resourceNames: ["nginx"]
  verbs: ["get", "list", "watch"]
